from __future__ import annotations

from personal_assistant.contracts.tools import ToolDefinition, define

TOOLS: tuple[ToolDefinition, ...] = (
    define(
        id="nextcloud.calendar.discover",
        domain="calendar",
        description="Erreichbare Nextcloud-Kalender read-only mit VEVENT-Unterstuetzung und Serverrechten auflisten",
        command="./scripts/assistant.sh calendar discover",
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="always",
        documentation_anchor="docs/DIRECT_CALENDAR.md",
        test_anchor="tests/test_direct_calendar_tool.py",
    ),
    define(
        id="nextcloud.calendar.configure",
        domain="calendar",
        description="Einen zuvor entdeckten Kalender nach ausdruecklicher Nutzerwahl konfigurieren; Aktualisierungsrecht nur mit --allow-update",
        command='./scripts/assistant.sh calendar configure --resource "<resource_id>" --allow-update --yes',
        mode="local-write",
        writes_external_data=False,
        approval="explicit-user-calendar-selection",
        availability="always",
        documentation_anchor="docs/DIRECT_CALENDAR.md",
        test_anchor="tests/test_direct_calendar_tool.py",
    ),
    define(
        id="nextcloud.calendar.status",
        domain="calendar",
        description="Konfiguration sowie Lese-, Anlege- und Aktualisierungsrechte des direkten Nextcloud-Kalenderwerkzeugs pruefen",
        command="./scripts/assistant.sh calendar status",
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="calendar",
        documentation_anchor="docs/DIRECT_CALENDAR.md",
        test_anchor="tests/test_direct_calendar_tool.py",
    ),
    define(
        id="nextcloud.calendar.list",
        domain="calendar",
        description="Termine aus dem freigegebenen Nextcloud-Kalender mit UID lesen",
        command="./scripts/assistant.sh calendar list --limit 100",
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="calendar-list",
        documentation_anchor="docs/DIRECT_CALENDAR.md",
        test_anchor="tests/test_direct_calendar_tool.py",
    ),
    define(
        id="nextcloud.calendar.search",
        domain="calendar",
        description="Termine nach Titel, Ort, Beschreibung oder UID suchen",
        command='./scripts/assistant.sh calendar search --query "<Suchbegriff>" --limit 50',
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="calendar-list",
        documentation_anchor="docs/DIRECT_CALENDAR.md",
        test_anchor="tests/test_direct_calendar_tool.py",
    ),
    define(
        id="nextcloud.calendar.update",
        domain="calendar",
        description="Einen zuvor eindeutig per UID ausgewaehlten Termin nach ausdruecklichem Nutzerauftrag ETag-geschuetzt aktualisieren; Serien nur mit gesonderter Freigabe",
        command='./scripts/assistant.sh calendar update --uid "<UID>" --expected-title "<aktueller Titel>" --start "<ISO-8601>" --yes',
        mode="write",
        writes_external_data=True,
        approval="explicit-user-calendar-update-etag-guarded",
        availability="calendar-update",
        documentation_anchor="docs/DIRECT_CALENDAR.md",
        test_anchor="tests/test_direct_calendar_tool.py",
    ),
    define(
        id="nextcloud.calendar.create",
        domain="calendar",
        description="Neuen Termin direkt in den freigegebenen Nextcloud-Kalender eintragen; calendar create akzeptiert kein --yes",
        command='./scripts/assistant.sh calendar create --title "<Titel>" --start "<ISO-8601>" --end "<ISO-8601>" --location "<Ort>" --description "<Beschreibung>"',
        mode="write",
        writes_external_data=True,
        approval="configured-calendar-create-only",
        availability="calendar-create",
        documentation_anchor="docs/DIRECT_CALENDAR.md",
        test_anchor="tests/test_direct_calendar_tool.py",
    ),
)
