from __future__ import annotations

from personal_assistant.contracts.tools import ToolDefinition, define

TOOLS: tuple[ToolDefinition, ...] = (
    define(
        id="nextcloud.contacts.discover",
        domain="contacts",
        description="Erreichbare Nextcloud-CardDAV-Adressbuecher read-only mit Serverrechten auflisten",
        command="./scripts/assistant.sh contacts discover",
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="always",
        documentation_anchor="docs/CARDDAV_CONTACTS.md",
        test_anchor="tests/test_carddav_contact_tools.py",
    ),
    define(
        id="nextcloud.contacts.configure",
        domain="contacts",
        description="Ein zuvor entdecktes Adressbuch nach ausdruecklicher Nutzerwahl konfigurieren; Aktualisierungsrecht nur mit --allow-update",
        command='./scripts/assistant.sh contacts configure --resource "<resource_id>" --allow-update --yes',
        mode="local-write",
        writes_external_data=False,
        approval="explicit-user-addressbook-selection",
        availability="always",
        documentation_anchor="docs/CARDDAV_CONTACTS.md",
        test_anchor="tests/test_carddav_contact_tools.py",
    ),
    define(
        id="nextcloud.contacts.status",
        domain="contacts",
        description="Konfiguration sowie Lese-, Anlege- und Aktualisierungsrechte des CardDAV-Kontaktwerkzeugs pruefen",
        command="./scripts/assistant.sh contacts status",
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="contacts",
        documentation_anchor="docs/CARDDAV_CONTACTS.md",
        test_anchor="tests/test_carddav_contact_tools.py",
    ),
    define(
        id="nextcloud.contacts.list",
        domain="contacts",
        description="Kontakte aus dem freigegebenen CardDAV-Adressbuch lesen",
        command="./scripts/assistant.sh contacts list --limit 100",
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="contacts-list",
        documentation_anchor="docs/CARDDAV_CONTACTS.md",
        test_anchor="tests/test_carddav_contact_tools.py",
    ),
    define(
        id="nextcloud.contacts.search",
        domain="contacts",
        description="Kontakte nach Name, E-Mail, Telefon oder Organisation suchen",
        command='./scripts/assistant.sh contacts search --query "<Suchbegriff>" --limit 50',
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="contacts-list",
        documentation_anchor="docs/CARDDAV_CONTACTS.md",
        test_anchor="tests/test_carddav_contact_tools.py",
    ),
    define(
        id="nextcloud.contacts.update",
        domain="contacts",
        description="Einen zuvor eindeutig gesuchten Kontakt per UID nach ausdruecklichem Nutzerauftrag ETag-geschuetzt aktualisieren; kein Loeschen oder Merge",
        command='./scripts/assistant.sh contacts update --uid "<UID>" --expected-name "<aktueller Name>" --phone "<neue Telefonnummer>" --yes',
        mode="write",
        writes_external_data=True,
        approval="explicit-user-contact-update-etag-guarded",
        availability="contacts-update",
        documentation_anchor="docs/CARDDAV_CONTACTS.md",
        test_anchor="tests/test_carddav_contact_tools.py",
    ),
    define(
        id="nextcloud.contacts.create",
        domain="contacts",
        description="Neuen Kontakt nach ausdruecklichem Nutzerauftrag create-only anlegen; bestehende Kontakte werden nicht veraendert",
        command='./scripts/assistant.sh contacts create --name "<Name>" --email "<E-Mail>" --phone "<Telefon>" --organization "<Firma>" --yes',
        mode="write",
        writes_external_data=True,
        approval="explicit-user-contact-create-only",
        availability="contacts-create",
        documentation_anchor="docs/CARDDAV_CONTACTS.md",
        test_anchor="tests/test_carddav_contact_tools.py",
    ),
    define(
        id="nextcloud.contacts.from-mail-preview",
        domain="contacts",
        description="Absender und konservativ erkannte Signaturdaten einer eindeutig ausgewaehlten Mail als Kontaktvorschlag pruefen",
        command='./scripts/assistant.sh contacts from-mail --folder "<Ordner>" --message-id "<Mail-ID>" --expected-subject "<Betreff>" --dry-run',
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="contacts-create",
        documentation_anchor="docs/CARDDAV_CONTACTS.md",
        test_anchor="tests/test_carddav_contact_tools.py",
    ),
    define(
        id="nextcloud.contacts.from-mail-create",
        domain="contacts",
        description="Kontakt aus einer eindeutig ausgewaehlten Mail nach Vorschau und ausdruecklichem Nutzerauftrag create-only anlegen",
        command='./scripts/assistant.sh contacts from-mail --folder "<Ordner>" --message-id "<Mail-ID>" --expected-subject "<Betreff>" --yes',
        mode="write",
        writes_external_data=True,
        approval="explicit-user-contact-from-mail-create-only",
        availability="contacts-create",
        documentation_anchor="docs/CARDDAV_CONTACTS.md",
        test_anchor="tests/test_carddav_contact_tools.py",
    ),
)
