from __future__ import annotations

from personal_assistant.contracts.tools import ToolDefinition, define

TOOLS: tuple[ToolDefinition, ...] = (
    define(
        id="mail.invoice-archive",
        domain="invoices",
        description="Sicher erkannte und virengepruefte Rechnungs-PDFs create-only ueber ActionPlan in Nextcloud archivieren",
        command="./scripts/assistant.sh mail run --limit 20",
        mode="write",
        writes_external_data=True,
        approval="automatic-create-only",
        availability="invoices",
        documentation_anchor="docs/INVOICE_OCR_REGISTER.md",
        test_anchor="tests/test_invoice_ocr_register.py",
    ),
    define(
        id="assistant.invoices.status",
        domain="invoices",
        description="Rechnungs-OCR, Abhaengigkeiten, Jahresregister und offene Prueffaelle anzeigen",
        command="./scripts/assistant.sh invoices status",
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="invoices",
        documentation_anchor="docs/INVOICE_OCR_REGISTER.md",
        test_anchor="tests/test_invoice_ocr_register.py",
    ),
    define(
        id="assistant.invoices.list",
        domain="invoices",
        description="Erkannte Rechnungsmetadaten eines Jahres ohne PDF-Inhalt anzeigen",
        command="./scripts/assistant.sh invoices list --year <YYYY> --limit 100",
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="invoices",
        documentation_anchor="docs/INVOICE_OCR_REGISTER.md",
        test_anchor="tests/test_invoice_ocr_register.py",
    ),
    define(
        id="assistant.invoices.review",
        domain="invoices",
        description="Unsichere Rechnungsdaten mit Hash und Erkennungsquelle zur Korrektur auflisten",
        command="./scripts/assistant.sh invoices review --limit 100",
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="invoices",
        documentation_anchor="docs/INVOICE_OCR_REGISTER.md",
        test_anchor="tests/test_invoice_ocr_register.py",
    ),
    define(
        id="assistant.invoices.export",
        domain="invoices",
        description="Jahresregister als semikolongetrennte UTF-8-CSV lokal erzeugen",
        command="./scripts/assistant.sh invoices export --year <YYYY>",
        mode="local-write",
        writes_external_data=False,
        approval="managed-invoice-register",
        availability="invoices",
        documentation_anchor="docs/INVOICE_OCR_REGISTER.md",
        test_anchor="tests/test_invoice_ocr_register.py",
    ),
    define(
        id="assistant.invoices.export-nextcloud",
        domain="invoices",
        description="Jahresregister nach ausdruecklichem Nutzerauftrag create-only nach Nextcloud exportieren",
        command="./scripts/assistant.sh invoices export --year <YYYY> --nextcloud --yes",
        mode="write",
        writes_external_data=True,
        approval="explicit-user-export-create-only",
        availability="invoices",
        documentation_anchor="docs/INVOICE_OCR_REGISTER.md",
        test_anchor="tests/test_invoice_ocr_register.py",
    ),
    define(
        id="assistant.invoices.backfill-preview",
        domain="invoices",
        description="Bereits archivierte Rechnungs-PDFs eines Jahres read-only erneut mit Text/OCR auswerten, ohne die Datenbank zu aendern",
        command="./scripts/assistant.sh invoices backfill --year <YYYY> --limit 500 --dry-run",
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="invoices",
        documentation_anchor="docs/INVOICE_OCR_REGISTER.md",
        test_anchor="tests/test_invoice_ocr_register.py",
    ),
    define(
        id="assistant.invoices.backfill",
        domain="invoices",
        description="Bereits archivierte Rechnungs-PDFs eines Jahres nach ausdruecklichem Nutzerauftrag neu auswerten und ins Jahresregister uebernehmen",
        command="./scripts/assistant.sh invoices backfill --year <YYYY> --limit 500 --yes",
        mode="local-write",
        writes_external_data=False,
        approval="explicit-user-invoice-backfill",
        availability="invoices",
        documentation_anchor="docs/INVOICE_OCR_REGISTER.md",
        test_anchor="tests/test_invoice_ocr_register.py",
    ),
    define(
        id="assistant.invoices.correct",
        domain="invoices",
        description="Unsichere Rechnungsmetadaten anhand des PDF-Hashs nach ausdruecklichem Nutzerauftrag korrigieren",
        command='./scripts/assistant.sh invoices correct --hash <SHA256> --date <YYYY-MM-DD> --number "<Nr>" --supplier "<Steller>" --category "<Kategorie>" --gross "<Betrag>" --yes',
        mode="local-write",
        writes_external_data=False,
        approval="explicit-user-correction",
        availability="invoices",
        documentation_anchor="docs/INVOICE_OCR_REGISTER.md",
        test_anchor="tests/test_invoice_ocr_register.py",
    ),
)
