from __future__ import annotations

from personal_assistant.contracts.tools import ToolDefinition, define

TOOLS: tuple[ToolDefinition, ...] = (
    define(
        id="mail.invoice-archive",
        domain="invoices",
        description="Virengepruefte Rechnungs-PDFs create-only archivieren und bei konfiguriertem Rechnungsworkflow das verwaltete Jahresregister ETag-geschuetzt synchronisieren",
        command="./scripts/assistant.sh mail run --limit 20",
        mode="write",
        writes_external_data=True,
        approval="configured-invoice-archive-and-managed-register-sync",
        availability="invoices",
        documentation_anchor="docs/INVOICE_OCR_REGISTER.md",
        test_anchor="tests/test_invoice_effect_contract_m101.py",
    ),
    define(
        id="assistant.invoices.status",
        domain="invoices",
        description="Rechnungs-OCR, Abhaengigkeiten, Jahresregister und offene Prueffaelle anzeigen",
        command="./scripts/assistant.sh invoices status",
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="invoices",
        documentation_anchor="docs/INVOICE_OCR_REGISTER.md",
        test_anchor="tests/test_invoice_ocr_register.py",
    ),
    define(
        id="assistant.invoices.audit",
        domain="invoices",
        description="Rechnungsbestand, Pflichtfeldluecken, Plausibilitaetsfehler, Extraktorversionen und Review-Pfadabweichungen ohne Dokumentinhalte aggregiert anzeigen",
        command="./scripts/assistant.sh invoices audit",
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="invoices",
        documentation_anchor="docs/INVOICE_OCR_REGISTER.md",
        test_anchor="tests/test_invoice_backlog_audit_m107.py",
    ),
    define(
        id="assistant.invoices.list",
        domain="invoices",
        description="Erkannte Rechnungsmetadaten eines Jahres ohne PDF-Inhalt anzeigen",
        command="./scripts/assistant.sh invoices list --year <YYYY> --limit 100",
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="invoices",
        documentation_anchor="docs/INVOICE_OCR_REGISTER.md",
        test_anchor="tests/test_invoice_ocr_register.py",
    ),
    define(
        id="assistant.invoices.review",
        domain="invoices",
        description="Unsichere Rechnungsdaten mit Hash und Erkennungsquelle zur Korrektur auflisten",
        command="./scripts/assistant.sh invoices review --limit 100",
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="invoices",
        documentation_anchor="docs/INVOICE_OCR_REGISTER.md",
        test_anchor="tests/test_invoice_ocr_register.py",
    ),
    define(
        id="assistant.invoices.export",
        domain="invoices",
        description="Jahresregister schreibfrei im Speicher rendern; SQLite und Nextcloud bleiben unveraendert",
        command="./scripts/assistant.sh invoices export --year <YYYY> --dry-run",
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="invoices",
        documentation_anchor="docs/INVOICE_OCR_REGISTER.md",
        test_anchor="tests/test_invoice_effect_contract_m101.py",
    ),
    define(
        id="assistant.invoices.export-nextcloud",
        domain="invoices",
        description="Verwaltetes Jahresregister nach ausdruecklichem Nutzerauftrag mit ETag-, SHA- und Schemaschutz in Nextcloud anlegen oder bedingt ersetzen",
        command="./scripts/assistant.sh invoices export --year <YYYY> --yes",
        mode="write",
        writes_external_data=True,
        approval="explicit-user-managed-register-replace",
        availability="invoices",
        documentation_anchor="docs/INVOICE_OCR_REGISTER.md",
        test_anchor="tests/test_invoice_effect_contract_m101.py",
    ),
    define(
        id="assistant.invoices.backfill-preview",
        domain="invoices",
        description="Archivierte Rechnungs-PDFs eines Jahres nur lesen und auswerten; SQLite und Nextcloud bleiben unveraendert",
        command="./scripts/assistant.sh invoices backfill --year <YYYY> --limit 500 --dry-run",
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="invoices",
        documentation_anchor="docs/INVOICE_OCR_REGISTER.md",
        test_anchor="tests/test_invoice_effect_contract_m101.py",
    ),
    define(
        id="assistant.invoices.backfill",
        domain="invoices",
        description="Archivierte Rechnungs-PDFs nach ausdruecklichem Nutzerauftrag neu auswerten, SQLite aendern und verwaltete Nextcloud-Jahresregister bedingt ersetzen",
        command="./scripts/assistant.sh invoices backfill --year <YYYY> --limit 500 --yes",
        mode="write",
        writes_external_data=True,
        approval="explicit-user-backfill-and-managed-register-replace",
        availability="invoices",
        documentation_anchor="docs/INVOICE_OCR_REGISTER.md",
        test_anchor="tests/test_invoice_effect_contract_m101.py",
    ),
    define(
        id="assistant.invoices.reprocess-preview",
        domain="invoices",
        description="Exakt review oder unklassifiziert markierte Rechnungen eines eindeutigen Quelljahres read-only neu bewerten und mit Alt/Neu-Evidenz sowie Vorschau-Digest anzeigen",
        command='./scripts/assistant.sh invoices reprocess --status "<review|unclassified>" --source-year <YYYY> --limit 100 --dry-run',
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="invoices",
        documentation_anchor="docs/INVOICE_OCR_REGISTER.md",
        test_anchor="tests/test_invoice_reprocess_preview_m105.py",
    ),
    define(
        id="assistant.invoices.reprocess-apply",
        domain="invoices",
        description="Genau einen unveraenderten, eindeutig verbesserten Reprocessing-Vorschlag nach explizitem Nutzerauftrag uebernehmen und betroffene verwaltete Jahresregister bedingt synchronisieren",
        command='./scripts/assistant.sh invoices reprocess-apply --hash "<SHA256>" --expected-preview-sha256 "<Digest>" --yes',
        mode="write",
        writes_external_data=True,
        approval="explicit-user-single-invoice-reprocess",
        availability="invoices",
        documentation_anchor="docs/INVOICE_OCR_REGISTER.md",
        test_anchor="tests/test_invoice_reprocess_apply_m106.py",
    ),
    define(
        id="assistant.invoices.correct",
        domain="invoices",
        description="Rechnungsmetadaten nach ausdruecklichem Nutzerauftrag in SQLite korrigieren und betroffene Nextcloud-Jahresregister bedingt ersetzen",
        command='./scripts/assistant.sh invoices correct --hash <SHA256> --date <YYYY-MM-DD> --number "<Nr>" --supplier "<Steller>" --category "<Kategorie>" --gross "<Betrag>" --yes',
        mode="write",
        writes_external_data=True,
        approval="explicit-user-correction-and-managed-register-replace",
        availability="invoices",
        documentation_anchor="docs/INVOICE_OCR_REGISTER.md",
        test_anchor="tests/test_invoice_effect_contract_m101.py",
    ),
)
