from __future__ import annotations

from personal_assistant.contracts.tools import ToolDefinition, define

TOOLS: tuple[ToolDefinition, ...] = (
    define(
        id="mail.status",
        domain="mail",
        description="Status des Mail-Werkzeugs anzeigen",
        command="./scripts/assistant.sh mail status",
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="always",
        documentation_anchor="skills/personal-assistant/SKILL.md",
        test_anchor="tests/test_agent_tool_architecture.py",
    ),
    define(
        id="mail.doctor",
        domain="mail",
        description="Mail-Werkzeug und Integrationen diagnostizieren",
        command="./scripts/assistant.sh mail doctor",
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="always",
        documentation_anchor="skills/personal-assistant/SKILL.md",
        test_anchor="tests/test_agent_tool_architecture.py",
    ),
    define(
        id="mail.review.status",
        domain="mail",
        description="Typisierte Review-Gruende, Quellen, Konfidenzbaender und Datenqualitaet ohne Mailinhalte aggregieren",
        command="./scripts/assistant.sh mail review status --days 7",
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="always",
        documentation_anchor="skills/personal-assistant/references/mail.md",
        test_anchor="tests/test_mail_review_m9.py",
    ),
    define(
        id="mail.review.list",
        domain="mail",
        description="Aktuelle Review-Metadaten nach einem geschlossenen typisierten Grund auflisten; keine Bodies oder Anhaenge",
        command='./scripts/assistant.sh mail review list --reason "<Grund>" --limit 50',
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="always",
        documentation_anchor="skills/personal-assistant/references/mail.md",
        test_anchor="tests/test_mail_review_m9.py",
    ),
    define(
        id="mail.review.suggest",
        domain="mail",
        description="Eine exakt ausgewaehlte Review-Mail read-only neu klassifizieren und Evidenz, Unsicherheit sowie naechsten erlaubten Schritt anzeigen",
        command='./scripts/assistant.sh mail review suggest --folder "<Ordner>" --message-id "<ID>" --expected-subject "<Betreff>"',
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="mail-move",
        documentation_anchor="skills/personal-assistant/references/mail.md",
        test_anchor="tests/test_mail_review_m9.py",
    ),
    define(
        id="mail.learning.status",
        domain="mail",
        description="Korrekturlernen, gemischte Absender, Musterkonflikte und Lernordner anzeigen",
        command="./scripts/assistant.sh mail learning status",
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="always",
        documentation_anchor="skills/personal-assistant/SKILL.md",
        test_anchor="tests/test_agent_tool_architecture.py",
    ),
    define(
        id="mail.learning.feedback",
        domain="mail",
        description="Letzte Nutzerkorrekturen mit Muster, Typ-Label und Match-Metadaten ohne Mailtext anzeigen",
        command="./scripts/assistant.sh mail learning feedback --limit 50",
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="always",
        documentation_anchor="skills/personal-assistant/SKILL.md",
        test_anchor="tests/test_agent_tool_architecture.py",
    ),
    define(
        id="mail.learning.not-spam",
        domain="mail",
        description="Nicht-Spam-Gegenbelege mit Ursprung INBOX-Restore oder Korrekturordner ohne Mailinhalte anzeigen",
        command="./scripts/assistant.sh mail learning not-spam --limit 100",
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="always",
        documentation_anchor="skills/personal-assistant/SKILL.md",
        test_anchor="tests/test_agent_tool_architecture.py",
    ),
    define(
        id="mail.learning.mixed-senders",
        domain="mail",
        description="Absender anzeigen, die nach Nutzerfeedback verschiedene Mailtypen senden",
        command="./scripts/assistant.sh mail learning mixed-senders --limit 100",
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="always",
        documentation_anchor="skills/personal-assistant/SKILL.md",
        test_anchor="tests/test_agent_tool_architecture.py",
    ),
    define(
        id="mail.learning.conflicts",
        domain="mail",
        description="Widerspruechliche Korrekturen mit stabiler conflict_id und betroffenen Feedback-IDs anzeigen",
        command="./scripts/assistant.sh mail learning conflicts --limit 100",
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="always",
        documentation_anchor="skills/personal-assistant/SKILL.md",
        test_anchor="tests/test_agent_tool_architecture.py",
    ),
    define(
        id="mail.learning.evaluate",
        domain="mail",
        description="Lernqualitaet chronologisch gegen die alte Absenderlogik und gespeicherte Klassifikationen auswerten",
        command="./scripts/assistant.sh mail learning evaluate --limit 5000",
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="always",
        documentation_anchor="skills/personal-assistant/SKILL.md",
        test_anchor="tests/test_agent_tool_architecture.py",
    ),
    define(
        id="mail.learning.dataset-export",
        domain="mail",
        description="Pseudonymisierten Lern-Datensatz ohne Mailtexte, Betreffe, Adressen oder Message-IDs lokal exportieren",
        command='./scripts/assistant.sh mail learning dataset-export --output "mail_agent/data/learning_dataset.json" --limit 5000',
        mode="local-write",
        writes_external_data=False,
        approval="learning-dataset-local-only",
        availability="always",
        documentation_anchor="skills/personal-assistant/SKILL.md",
        test_anchor="tests/test_agent_tool_architecture.py",
    ),
    define(
        id="mail.learning.folder-list",
        domain="mail",
        description="Kontrollierte dynamische Korrektur-Unterordner anzeigen",
        command="./scripts/assistant.sh mail learning folder-list",
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="always",
        documentation_anchor="skills/personal-assistant/SKILL.md",
        test_anchor="tests/test_agent_tool_architecture.py",
    ),
    define(
        id="mail.learning.folder-create",
        domain="mail",
        description="Korrektur-Unterordner nach ausdruecklichem Nutzerauftrag anlegen und registrieren",
        command='./scripts/assistant.sh mail learning folder-create --parent "<routine|important|spam|not-spam>" --name "<Name>" --label "<Typ>" --yes',
        mode="write",
        writes_external_data=True,
        approval="explicit-user-create-correction-folder",
        availability="always",
        documentation_anchor="skills/personal-assistant/SKILL.md",
        test_anchor="tests/test_agent_tool_architecture.py",
    ),
    define(
        id="mail.learning.folder-disable",
        domain="mail",
        description="Lernzuordnung eines dynamischen Korrekturordners nach Nutzerauftrag deaktivieren, ohne den IMAP-Ordner zu loeschen",
        command='./scripts/assistant.sh mail learning folder-disable --folder "<Ordner>" --yes',
        mode="local-write",
        writes_external_data=False,
        approval="explicit-user-disable-learning-folder",
        availability="always",
        documentation_anchor="skills/personal-assistant/SKILL.md",
        test_anchor="tests/test_agent_tool_architecture.py",
    ),
    define(
        id="mail.sources.configure",
        domain="mail",
        description="Primaer- und Provider-Spam-/Quarantaeneordner kontrolliert konfigurieren",
        command='./scripts/assistant.sh setup mail-sources --primary "INBOX" --quarantine-folder "Spamverdacht"',
        mode="local-write",
        writes_external_data=False,
        approval="safe-settings",
        availability="always",
        documentation_anchor="skills/personal-assistant/SKILL.md",
        test_anchor="tests/test_agent_tool_architecture.py",
    ),
    define(
        id="mail.dry-run",
        domain="mail",
        description="Mail-Pipeline ohne externe Aenderungen pruefen",
        command="./scripts/assistant.sh mail dry-run --limit 20",
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="always",
        documentation_anchor="skills/personal-assistant/SKILL.md",
        test_anchor="tests/test_agent_tool_architecture.py",
    ),
    define(
        id="mail.run",
        domain="mail",
        description="Mail-Pipeline produktiv ausfuehren",
        command="./scripts/assistant.sh mail run --limit 20",
        mode="write",
        writes_external_data=True,
        approval="configured-policy",
        availability="always",
        documentation_anchor="skills/personal-assistant/SKILL.md",
        test_anchor="tests/test_agent_tool_architecture.py",
    ),
    define(
        id="mail.spam-review",
        domain="mail",
        description="Provider-Spamordner als Quarantaene pruefen und klare Fehlklassifizierungen retten",
        command="./scripts/assistant.sh mail spam-review --limit 20",
        mode="write",
        writes_external_data=True,
        approval="quarantine-rescue-policy",
        availability="always",
        documentation_anchor="skills/personal-assistant/SKILL.md",
        test_anchor="tests/test_agent_tool_architecture.py",
    ),
    define(
        id="mail.move-status",
        domain="mail",
        description="Berechtigungen, vorhandene Ordner und gesperrte Ziele des Mail-Verschiebewerkzeugs pruefen",
        command="./scripts/assistant.sh mail move-status",
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="mail-move",
        documentation_anchor="skills/personal-assistant/SKILL.md",
        test_anchor="tests/test_agent_tool_architecture.py",
    ),
    define(
        id="mail.list",
        domain="mail",
        description="Mail-Metadaten eines vorhandenen Ordners lesen, um eine Mail eindeutig auszuwaehlen",
        command='./scripts/assistant.sh mail list --folder "<Ordner>" --limit 50',
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="mail-move",
        documentation_anchor="skills/personal-assistant/SKILL.md",
        test_anchor="tests/test_agent_tool_architecture.py",
    ),
    define(
        id="mail.search",
        domain="mail",
        description="Mails serverseitig in Absender, Betreff und Text ordneruebergreifend einschliesslich Review-Ordnern durchsuchen; Vollstaendigkeit und Ergebnislimit in der Rueckgabe pruefen",
        command='./scripts/assistant.sh mail search --query "<Suchbegriff>" --limit 50',
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="mail-move",
        documentation_anchor="skills/personal-assistant/SKILL.md",
        test_anchor="tests/test_agent_tool_architecture.py",
    ),
    define(
        id="mail.read",
        domain="mail",
        description="Eine per Ordner und Mail-ID eindeutig ausgewaehlte Mail read-only mit Inhalt lesen",
        command='./scripts/assistant.sh mail read --folder "<Ordner>" --message-id "<ID>" --expected-subject "<Betreff>"',
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="mail-move",
        documentation_anchor="skills/personal-assistant/SKILL.md",
        test_anchor="tests/test_agent_tool_architecture.py",
    ),
    define(
        id="mail.reply-draft",
        domain="mail",
        description="Antwortentwurf zu einer eindeutig ausgewaehlten Mail anlegen und vollstaendig anzeigen",
        command='./scripts/assistant.sh mail reply-draft --folder "<Ordner>" --message-id "<ID>" --expected-subject "<Betreff>" --body "<Entwurf>"',
        mode="local-write",
        writes_external_data=False,
        approval="draft-only-no-send",
        availability="mail-move",
        documentation_anchor="skills/personal-assistant/SKILL.md",
        test_anchor="tests/test_agent_tool_architecture.py",
    ),
    define(
        id="mail.reply-send",
        domain="mail",
        description="Nur einen zuvor angezeigten Antwortentwurf nach ausdruecklicher Nutzerfreigabe versenden",
        command='./scripts/assistant.sh mail reply-send --draft-id "<Entwurfs-ID>" --yes',
        mode="write",
        writes_external_data=True,
        approval="explicit-user-approved-presented-draft",
        availability="mail-move",
        documentation_anchor="skills/personal-assistant/SKILL.md",
        test_anchor="tests/test_agent_tool_architecture.py",
    ),
    define(
        id="mail.compose-draft",
        domain="mail",
        description="Vollstaendigen Entwurf fuer eine neue Mail anlegen und ohne Versand anzeigen",
        command='./scripts/assistant.sh mail compose-draft --to "<Empfaenger>" --subject "<Betreff>" --body "<Entwurf>"',
        mode="local-write",
        writes_external_data=False,
        approval="draft-only-no-send",
        availability="mail-move",
        documentation_anchor="skills/personal-assistant/SKILL.md",
        test_anchor="tests/test_agent_tool_architecture.py",
    ),
    define(
        id="mail.compose-send",
        domain="mail",
        description="Nur einen zuvor angezeigten neuen Mailentwurf nach ausdruecklicher Nutzerfreigabe versenden",
        command='./scripts/assistant.sh mail compose-send --draft-id "<Entwurfs-ID>" --yes',
        mode="write",
        writes_external_data=True,
        approval="explicit-user-approved-presented-draft",
        availability="mail-move",
        documentation_anchor="skills/personal-assistant/SKILL.md",
        test_anchor="tests/test_agent_tool_architecture.py",
    ),
    define(
        id="mail.move",
        domain="mail",
        description="Eine eindeutig per Mail-ID ausgewaehlte Mail zwischen vorhandenen, nicht-destruktiven Ordnern verschieben",
        command='./scripts/assistant.sh mail move --source "<Quelle>" --destination "<Ziel>" --message-id "<ID>" --expected-subject "<Betreff>"',
        mode="write",
        writes_external_data=True,
        approval="configured-mail-organize-single-message",
        availability="mail-move",
        documentation_anchor="skills/personal-assistant/SKILL.md",
        test_anchor="tests/test_agent_tool_architecture.py",
    ),
    define(
        id="mail.calendar-command",
        domain="mail",
        description="Termin aus einer autorisierten Befehlsmail in den konfigurierten Nextcloud-Kalender eintragen",
        command="Subject: {calendar_subject_prefix} <Terminbeschreibung>",
        mode="write",
        writes_external_data=True,
        approval="trusted-owner-command",
        availability="calendar-mail",
        documentation_anchor="skills/personal-assistant/SKILL.md",
        test_anchor="tests/test_agent_tool_architecture.py",
    ),
)
