from __future__ import annotations

from personal_assistant.contracts.tools import ToolDefinition, define

TOOLS: tuple[ToolDefinition, ...] = (
    define(
        id="nextcloud.list",
        domain="nextcloud",
        description="Dateien innerhalb der erlaubten Nextcloud-Wurzeln auflisten",
        command='./scripts/assistant.sh nextcloud list --path "Assistent"',
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="always",
        documentation_anchor="docs/NEXTCLOUD.md",
        test_anchor="tests/test_nextcloud_workspace_tools.py",
    ),
    define(
        id="nextcloud.sync",
        domain="nextcloud",
        description="Nextcloud-Inhalte inkrementell in den lokalen Index synchronisieren",
        command="./scripts/assistant.sh nextcloud sync",
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="always",
        documentation_anchor="docs/NEXTCLOUD.md",
        test_anchor="tests/test_nextcloud_workspace_tools.py",
    ),
    define(
        id="nextcloud.workspace.mkdir",
        domain="nextcloud",
        description="Ordner innerhalb des Nextcloud-Arbeitsbereichs idempotent anlegen",
        command='./scripts/assistant.sh nextcloud mkdir --path "{workspace_root}/<Ordner>"',
        mode="write",
        writes_external_data=True,
        approval="workspace-create",
        availability="workspace-mkdir",
        documentation_anchor="docs/NEXTCLOUD.md",
        test_anchor="tests/test_nextcloud_workspace_tools.py",
    ),
    define(
        id="nextcloud.workspace.write-text",
        domain="nextcloud",
        description="Neue UTF-8-Textdatei create-only aus stdin im Nextcloud-Arbeitsbereich anlegen",
        command='printf "%s" "<Inhalt>" | ./scripts/assistant.sh nextcloud write-text --path "{workspace_root}/<Datei>.md"',
        mode="write",
        writes_external_data=True,
        approval="workspace-create-only",
        availability="workspace-write-text",
        documentation_anchor="docs/NEXTCLOUD.md",
        test_anchor="tests/test_nextcloud_workspace_tools.py",
    ),
    define(
        id="nextcloud.workspace.upload",
        domain="nextcloud",
        description="Virengepruefte neue Datei create-only aus der kontrollierten Workspace-Outbox nach Nextcloud hochladen",
        command='./scripts/assistant.sh nextcloud upload --local "personal_assistant/data/workspace_outbox/<Datei>" --path "{workspace_root}/<Ziel>"',
        mode="write",
        writes_external_data=True,
        approval="workspace-create-only",
        availability="workspace-upload",
        documentation_anchor="docs/NEXTCLOUD.md",
        test_anchor="tests/test_nextcloud_workspace_tools.py",
    ),
    define(
        id="nextcloud.workspace.move",
        domain="nextcloud",
        description="Datei oder Ordner innerhalb des Arbeitsbereichs ohne Ueberschreiben verschieben oder umbenennen",
        command='./scripts/assistant.sh nextcloud move --source "{workspace_root}/<Quelle>" --destination "{workspace_root}/<Ziel>"',
        mode="write",
        writes_external_data=True,
        approval="workspace-organize-no-overwrite",
        availability="workspace-move",
        documentation_anchor="docs/NEXTCLOUD.md",
        test_anchor="tests/test_nextcloud_workspace_tools.py",
    ),
    define(
        id="nextcloud.workspace.configure",
        domain="nextcloud",
        description="Nextcloud-Arbeitsbereich und Rechte konfigurieren",
        command='./scripts/assistant.sh setup workspace --root "{workspace_root}" --approve-permissions',
        mode="local-write",
        writes_external_data=False,
        approval="explicit-user-permission",
        availability="workspace",
        documentation_anchor="docs/NEXTCLOUD.md",
        test_anchor="tests/test_nextcloud_workspace_tools.py",
    ),
)
