from __future__ import annotations

from personal_assistant.contracts.tools import ToolDefinition, define

TOOLS: tuple[ToolDefinition, ...] = (
    define(
        id="nextcloud.deck.orders.status",
        domain="orders",
        description="Nextcloud Deck-Bestellboard, Rechte und lokale Bestelldatenbank pruefen",
        command="./scripts/assistant.sh orders status",
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="orders",
        documentation_anchor="docs/DECK_ORDERS.md",
        test_anchor="tests/test_order_deck_tool.py",
    ),
    define(
        id="nextcloud.deck.orders.list",
        domain="orders",
        description="Laufende Bestellungen mit Status, Liefertermin, Tracking und Retouren ausgeben",
        command="./scripts/assistant.sh orders list --limit 100",
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="orders",
        documentation_anchor="docs/DECK_ORDERS.md",
        test_anchor="tests/test_order_deck_tool.py",
    ),
    define(
        id="nextcloud.deck.discover",
        domain="orders",
        description="Verfuegbare Nextcloud Deck-Boards read-only auflisten",
        command="./scripts/assistant.sh deck discover",
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="orders",
        documentation_anchor="docs/DECK_ORDERS.md",
        test_anchor="tests/test_order_deck_tool.py",
    ),
    define(
        id="mail.orders.import",
        domain="orders",
        description="Bereits lokal indexierte Mails kontrolliert auf laufende Bestellungen nachklassifizieren",
        command="./scripts/assistant.sh mail orders-import --limit 500 --dry-run",
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="orders",
        documentation_anchor="docs/DECK_ORDERS.md",
        test_anchor="tests/test_order_deck_tool.py",
    ),
    define(
        id="nextcloud.deck.orders.sync",
        domain="orders",
        description="Ausstehende Aktualisierungen agentenverwalteter Bestellkarten nach Nextcloud Deck synchronisieren",
        command="./scripts/assistant.sh orders sync --limit 500",
        mode="write",
        writes_external_data=True,
        approval="managed-order-cards-only",
        availability="orders",
        documentation_anchor="docs/DECK_ORDERS.md",
        test_anchor="tests/test_order_deck_tool.py",
    ),
    define(
        id="nextcloud.deck.orders.due-date-preview",
        domain="orders",
        description="Agentenverwaltete Bestellkarten ohne Faelligkeitsdatum read-only pruefen und plausible Quellen anzeigen",
        command="./scripts/assistant.sh orders due-date-backfill --limit 500 --dry-run",
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="orders",
        documentation_anchor="docs/DECK_ORDERS.md",
        test_anchor="tests/test_order_deck_tool.py",
    ),
    define(
        id="nextcloud.deck.orders.due-date-backfill",
        domain="orders",
        description="Fehlende Faelligkeitsdaten agentenverwalteter Bestellkarten nach ausdruecklichem Auftrag ergaenzen",
        command="./scripts/assistant.sh orders due-date-backfill --limit 500 --yes",
        mode="write",
        writes_external_data=True,
        approval="managed-order-cards-missing-due-only",
        availability="orders",
        documentation_anchor="docs/DECK_ORDERS.md",
        test_anchor="tests/test_order_deck_tool.py",
    ),
)
