from __future__ import annotations

from personal_assistant.contracts.tools import ToolDefinition, define

TOOLS: tuple[ToolDefinition, ...] = (
    define(
        id="portfolio.status",
        domain="portfolio",
        description="Depotbestand, Watchlist, Kursabdeckung und Datenfrische anzeigen",
        command="./scripts/assistant.sh portfolio status",
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="always",
        documentation_anchor="docs/PORTFOLIO_ADVISOR.md",
        test_anchor="tests/test_portfolio_tool.py",
    ),
    define(
        id="portfolio.setup",
        domain="portfolio",
        description="Portfolio-Monitor fuer den bezahlten EODHD-Zugang auf 15-Minuten-Abrufe konfigurieren; API-Schluessel und Job bleiben getrennt",
        command="./scripts/assistant.sh setup portfolio --provider eodhd --interval-minutes 15 --approve-permissions",
        mode="local-write",
        writes_external_data=False,
        approval="explicit-user-permission-setup",
        availability="always",
        documentation_anchor="docs/PORTFOLIO_ADVISOR.md",
        test_anchor="tests/test_portfolio_tool.py",
    ),
    define(
        id="portfolio.doctor",
        domain="portfolio",
        description="Portfolio-Datenbank, Anbieter-Konfiguration und Pflichtkurse pruefen",
        command="./scripts/assistant.sh portfolio doctor",
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="always",
        documentation_anchor="docs/PORTFOLIO_ADVISOR.md",
        test_anchor="tests/test_portfolio_tool.py",
    ),
    define(
        id="portfolio.import.pp",
        domain="portfolio",
        description="ClamAV-gepruefte Portfolio-Performance-XML zuerst als Vorschau importieren",
        command='./scripts/assistant.sh portfolio import-pp --file "<Datei-im-Importordner>" --dry-run',
        mode="local-write",
        writes_external_data=False,
        approval="explicit-user-import-with-preview",
        availability="always",
        documentation_anchor="docs/PORTFOLIO_ADVISOR.md",
        test_anchor="tests/test_portfolio_tool.py",
    ),
    define(
        id="portfolio.import.pp.confirm",
        domain="portfolio",
        description="Zuvor geprueften Portfolio-Snapshot nach ausdruecklichem Nutzerauftrag lokal importieren",
        command='./scripts/assistant.sh portfolio import-pp --file "<Datei-im-Importordner>" --yes',
        mode="local-write",
        writes_external_data=False,
        approval="explicit-user-confirmed-import",
        availability="always",
        documentation_anchor="docs/PORTFOLIO_ADVISOR.md",
        test_anchor="tests/test_portfolio_tool.py",
    ),
    define(
        id="portfolio.import.csv",
        domain="portfolio",
        description="ClamAV-geprueften DKB-CSV-Depotsnapshot aus dem kontrollierten Importordner zuerst als Vorschau einlesen",
        command='./scripts/assistant.sh portfolio import-csv --file "<Datei-im-Importordner>" --dry-run',
        mode="local-write",
        writes_external_data=False,
        approval="explicit-user-import-with-preview",
        availability="always",
        documentation_anchor="docs/PORTFOLIO_ADVISOR.md",
        test_anchor="tests/test_portfolio_tool.py",
    ),
    define(
        id="portfolio.import.csv.nextcloud",
        domain="portfolio",
        description="Exakt ausgewaehlte datierte DKB-CSV aus dem konfigurierten Nextcloud-Portfolioordner herunterladen, scannen und als Vorschau einlesen",
        command='./scripts/assistant.sh portfolio import-csv --nextcloud-path "Assistent/Finanzen/Portfolio/<Datei-DD.MM.YYYY.csv>" --dry-run',
        mode="local-write",
        writes_external_data=False,
        approval="explicit-user-import-with-preview",
        availability="always",
        documentation_anchor="docs/PORTFOLIO_ADVISOR.md",
        test_anchor="tests/test_portfolio_tool.py",
    ),
    define(
        id="portfolio.import.csv.confirm",
        domain="portfolio",
        description="Zuvor geprueften lokalen DKB-CSV-Depotsnapshot nach ausdruecklichem Nutzerauftrag importieren",
        command='./scripts/assistant.sh portfolio import-csv --file "<Datei-im-Importordner>" --yes',
        mode="local-write",
        writes_external_data=False,
        approval="explicit-user-confirmed-import",
        availability="always",
        documentation_anchor="docs/PORTFOLIO_ADVISOR.md",
        test_anchor="tests/test_portfolio_tool.py",
    ),
    define(
        id="portfolio.import.csv.nextcloud.confirm",
        domain="portfolio",
        description="Zuvor geprueften DKB-CSV-Depotsnapshot aus dem exakten Nextcloud-Pfad nach ausdruecklichem Nutzerauftrag importieren",
        command='./scripts/assistant.sh portfolio import-csv --nextcloud-path "Assistent/Finanzen/Portfolio/<Datei-DD.MM.YYYY.csv>" --yes',
        mode="local-write",
        writes_external_data=False,
        approval="explicit-user-confirmed-import",
        availability="always",
        documentation_anchor="docs/PORTFOLIO_ADVISOR.md",
        test_anchor="tests/test_portfolio_tool.py",
    ),
    define(
        id="portfolio.holdings",
        domain="portfolio",
        description="Eigene Aktien, Wertpapiere und Depotpositionen aus dem letzten unveraenderlich gespeicherten Snapshot anzeigen",
        command="./scripts/assistant.sh portfolio holdings",
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="always",
        documentation_anchor="docs/PORTFOLIO_ADVISOR.md",
        test_anchor="tests/test_portfolio_tool.py",
    ),
    define(
        id="portfolio.valuation",
        domain="portfolio",
        description="Aktuellen Depotwert, Einstand und Gewinn deterministisch immer in EUR aus gespeicherten EODHD-Aktienkursen und zeitgestempelten EODHD-Wechselkursen berechnen; bei fehlender Umrechnung fail-closed",
        command="./scripts/assistant.sh portfolio valuation",
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="always",
        documentation_anchor="docs/PORTFOLIO_ADVISOR.md",
        test_anchor="tests/test_portfolio_tool.py",
    ),
    define(
        id="portfolio.watchlist",
        domain="portfolio",
        description="Watchlist und bestaetigte ISIN/Symbol/MIC-Zuordnungen anzeigen",
        command="./scripts/assistant.sh portfolio watchlist list",
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="always",
        documentation_anchor="docs/PORTFOLIO_ADVISOR.md",
        test_anchor="tests/test_portfolio_tool.py",
    ),
    define(
        id="portfolio.mapping.suggest",
        domain="portfolio",
        description="Bei bereits bekannter ISIN immer diese Operation mit dem Pflichtargument isin verwenden: exakte EODHD-ISIN-Treffer abrufen, Ollama nur aus providerseitig belegten Kandidaten auswaehlen lassen und die vollstaendige genehmigungspflichtige watchlist-add-Folgeaktion liefern",
        command='./scripts/assistant.sh portfolio mapping suggest --isin "<ISIN>"',
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="always",
        documentation_anchor="docs/PORTFOLIO_ADVISOR.md",
        test_anchor="tests/test_portfolio_tool.py",
    ),
    define(
        id="portfolio.mapping.discover",
        domain="portfolio",
        description="Nur wenn noch keine ISIN bekannt ist, diese Operation mit dem Pflichtargument query verwenden: Wertpapiername oder Symbol bei EODHD suchen, eine eindeutige providerseitige ISIN ermitteln und daraus Vorschlag sowie vollstaendige genehmigungspflichtige watchlist-add-Folgeaktion erzeugen",
        command='./scripts/assistant.sh portfolio mapping suggest --query "<Unternehmen-oder-Symbol>"',
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="always",
        documentation_anchor="docs/PORTFOLIO_ADVISOR.md",
        test_anchor="tests/test_portfolio_tool.py",
    ),
    define(
        id="portfolio.watchlist.add",
        domain="portfolio",
        description="Wertpapier nur mit den unveraenderten Feldern einer explizit bestaetigten Mapping-Folgeaktion aufnehmen; portfolio mapping add existiert nicht",
        command='./scripts/assistant.sh portfolio watchlist add --isin "<ISIN>" --name "<Name>" --symbol "<Symbol>" --mic "<MIC>" --currency "<ISO>" --yes',
        mode="local-write",
        writes_external_data=False,
        approval="explicit-user-watchlist-change",
        availability="always",
        documentation_anchor="docs/PORTFOLIO_ADVISOR.md",
        test_anchor="tests/test_portfolio_tool.py",
    ),
    define(
        id="portfolio.watchlist.disable",
        domain="portfolio",
        description="Watchlist-Eintrag nach Nutzerauftrag deaktivieren, ohne Historie zu loeschen",
        command='./scripts/assistant.sh portfolio watchlist disable --isin "<ISIN>" --yes',
        mode="local-write",
        writes_external_data=False,
        approval="explicit-user-watchlist-change",
        availability="always",
        documentation_anchor="docs/PORTFOLIO_ADVISOR.md",
        test_anchor="tests/test_portfolio_tool.py",
    ),
    define(
        id="portfolio.quotes.status",
        domain="portfolio",
        description="Pflichtkurs-Abdeckung, Alter und letzten Abrufstatus anzeigen",
        command="./scripts/assistant.sh portfolio quotes status",
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="always",
        documentation_anchor="docs/PORTFOLIO_ADVISOR.md",
        test_anchor="tests/test_portfolio_tool.py",
    ),
    define(
        id="portfolio.quotes.get",
        domain="portfolio",
        description="Letzten gespeicherten Kurswert samt verpflichtendem aktuellem EUR-Wert, FX-Nachweis, Quelle und Zeitstempel fuer eine exakte ISIN anzeigen",
        command='./scripts/assistant.sh portfolio quotes get --isin "<ISIN>"',
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="always",
        documentation_anchor="docs/PORTFOLIO_ADVISOR.md",
        test_anchor="tests/test_portfolio_tool.py",
    ),
    define(
        id="portfolio.quotes.refresh",
        domain="portfolio",
        description="Faellige EODHD-Live/Delayed-Kurse gebuendelt abrufen, Quellzeit und Empfangszeit speichern und Pflichtluecken fail-closed melden",
        command="./scripts/assistant.sh portfolio quotes refresh",
        mode="local-write",
        writes_external_data=False,
        approval="scheduled-market-data-refresh",
        availability="always",
        documentation_anchor="docs/PORTFOLIO_ADVISOR.md",
        test_anchor="tests/test_portfolio_tool.py",
    ),
    define(
        id="portfolio.quotes.refresh.force",
        domain="portfolio",
        description="Kursabruf fuer eine gezielte Diagnose vor dem naechsten Faelligkeitszeitpunkt erzwingen",
        command="./scripts/assistant.sh portfolio quotes refresh --force",
        mode="local-write",
        writes_external_data=False,
        approval="explicit-user-diagnostic-refresh",
        availability="always",
        documentation_anchor="docs/PORTFOLIO_ADVISOR.md",
        test_anchor="tests/test_portfolio_tool.py",
    ),
    define(
        id="portfolio.analyze",
        domain="portfolio",
        description="Gespeicherte Kursreihe mit deterministischen Trendindikatoren analysieren",
        command='./scripts/assistant.sh portfolio analyze --isin "<ISIN>"',
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="always",
        documentation_anchor="docs/PORTFOLIO_ADVISOR.md",
        test_anchor="tests/test_portfolio_tool.py",
    ),
    define(
        id="portfolio.research.status",
        domain="portfolio",
        description="EODHD-Researchkonfiguration, Tarifnachweis, Modelle und letzten Lauf anzeigen",
        command="./scripts/assistant.sh portfolio research status",
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="always",
        documentation_anchor="docs/PORTFOLIO_ADVISOR.md",
        test_anchor="tests/test_portfolio_research.py",
    ),
    define(
        id="portfolio.research.models",
        domain="portfolio",
        description="Versionierte Analysemodelle, Kennzahlgewichte, Mindestabdeckung und Urteilsgrenzen anzeigen",
        command="./scripts/assistant.sh portfolio research models",
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="always",
        documentation_anchor="docs/PORTFOLIO_ADVISOR.md",
        test_anchor="tests/test_portfolio_research.py",
    ),
    define(
        id="portfolio.research.screen",
        domain="portfolio",
        description="Neue EODHD-Aktien mit allowlist-gefiltertem Screener suchen, Fundamental- und EOD-Daten deterministisch bewerten und den belegten Lauf lokal protokollieren",
        command='./scripts/assistant.sh portfolio research screen --strategy "<auto|balanced|quality-value|quality-growth|dividend-quality>" --exchange "<Boerse-optional>" --sector "<Sektor-optional>" --limit 5',
        mode="local-write",
        writes_external_data=False,
        approval="provider-research-cache-local-only",
        availability="always",
        documentation_anchor="docs/PORTFOLIO_ADVISOR.md",
        test_anchor="tests/test_portfolio_research.py",
    ),
    define(
        id="portfolio.research.analyze",
        domain="portfolio",
        description="Eine exakte ISIN anhand providergebundener EODHD-Fundamental- und EOD-Historie mit dem versionierten Mehrfaktormodell analysieren",
        command='./scripts/assistant.sh portfolio research analyze --isin "<ISIN>" --strategy "<auto|balanced|quality-value|quality-growth|dividend-quality>"',
        mode="local-write",
        writes_external_data=False,
        approval="provider-research-cache-local-only",
        availability="always",
        documentation_anchor="docs/PORTFOLIO_ADVISOR.md",
        test_anchor="tests/test_portfolio_research.py",
    ),
    define(
        id="portfolio.research.history",
        domain="portfolio",
        description="Lokal protokollierte Research-Laeufe samt Modellversion und Fehlerstatus anzeigen",
        command="./scripts/assistant.sh portfolio research history --limit 20",
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="always",
        documentation_anchor="docs/PORTFOLIO_ADVISOR.md",
        test_anchor="tests/test_portfolio_research.py",
    ),
    define(
        id="portfolio.philosophy.show",
        domain="portfolio",
        description="Letzte ausdruecklich bestaetigte Version der persoenlichen Investmentphilosophie anzeigen",
        command="./scripts/assistant.sh portfolio philosophy show",
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="always",
        documentation_anchor="docs/PORTFOLIO_ADVISOR.md",
        test_anchor="tests/test_portfolio_research.py",
    ),
    define(
        id="portfolio.philosophy.review",
        domain="portfolio",
        description="Depotkonzentration und Lernsignale nur gegen bestaetigte Profilgrenzen und belegte EUR-/Research-Daten kritisch pruefen",
        command="./scripts/assistant.sh portfolio philosophy review",
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="always",
        documentation_anchor="docs/PORTFOLIO_ADVISOR.md",
        test_anchor="tests/test_portfolio_research.py",
    ),
    define(
        id="portfolio.philosophy.history",
        domain="portfolio",
        description="Append-only Historie der bestaetigten Investmentprofil-Versionen anzeigen",
        command="./scripts/assistant.sh portfolio philosophy history --limit 20",
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="always",
        documentation_anchor="docs/PORTFOLIO_ADVISOR.md",
        test_anchor="tests/test_portfolio_research.py",
    ),
    define(
        id="portfolio.philosophy.set",
        domain="portfolio",
        description="Eine vollstaendige neue Investmentprofil-Version nach ausdruecklicher Bestaetigung append-only speichern; Beobachtungen duerfen sie nie automatisch aendern",
        command='./scripts/assistant.sh portfolio philosophy set --risk-tolerance "<conservative|balanced|growth>" --horizon-years <1-50> --strategy "<balanced|quality-value|quality-growth|dividend-quality>" --max-position-pct "<Prozent>" --max-sector-pct "<Prozent>" --preferred-sectors "<Kommaliste>" --excluded-sectors "<Kommaliste>" --notes "<Notiz>" --yes',
        mode="local-write",
        writes_external_data=False,
        approval="explicit-user-investment-profile-change",
        availability="always",
        documentation_anchor="docs/PORTFOLIO_ADVISOR.md",
        test_anchor="tests/test_portfolio_research.py",
    ),
    define(
        id="portfolio.philosophy.feedback",
        domain="portfolio",
        description="Begruendetes Nutzerfeedback zu einer gespeicherten Research-Kandidaten-ID append-only erfassen, ohne das deklarierte Profil automatisch zu aendern",
        command='./scripts/assistant.sh portfolio philosophy feedback --candidate-id "<Research-Kandidaten-ID>" --decision "<interested|rejected|watch|bought|sold>" --reason "<Begruendung>" --yes',
        mode="local-write",
        writes_external_data=False,
        approval="explicit-user-investment-feedback",
        availability="always",
        documentation_anchor="docs/PORTFOLIO_ADVISOR.md",
        test_anchor="tests/test_portfolio_research.py",
    ),
    define(
        id="portfolio.alerts",
        domain="portfolio",
        description="Kursmarken und deduplizierte Uebertrittsereignisse anzeigen",
        command="./scripts/assistant.sh portfolio alerts list",
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="always",
        documentation_anchor="docs/PORTFOLIO_ADVISOR.md",
        test_anchor="tests/test_portfolio_tool.py",
    ),
    define(
        id="portfolio.alerts.add",
        domain="portfolio",
        description="Kursmarke mit Hysterese und Abklingzeit nach Nutzerauftrag anlegen",
        command='./scripts/assistant.sh portfolio alerts add --isin "<ISIN>" --direction "<above|below>" --threshold "<Kurs>" --currency "<ISO>" --yes',
        mode="local-write",
        writes_external_data=False,
        approval="explicit-user-alert-change",
        availability="always",
        documentation_anchor="docs/PORTFOLIO_ADVISOR.md",
        test_anchor="tests/test_portfolio_tool.py",
    ),
    define(
        id="portfolio.alerts.disable",
        domain="portfolio",
        description="Kursalarm nach Nutzerauftrag deaktivieren, ohne Ereignishistorie zu loeschen",
        command='./scripts/assistant.sh portfolio alerts disable --id "<Regel-ID>" --yes',
        mode="local-write",
        writes_external_data=False,
        approval="explicit-user-alert-change",
        availability="always",
        documentation_anchor="docs/PORTFOLIO_ADVISOR.md",
        test_anchor="tests/test_portfolio_tool.py",
    ),
    define(
        id="portfolio.performance",
        domain="portfolio",
        description="Signalqualitaet getrennt von der technischen Agentengesundheit auswerten",
        command="./scripts/assistant.sh portfolio performance",
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="always",
        documentation_anchor="docs/PORTFOLIO_ADVISOR.md",
        test_anchor="tests/test_portfolio_tool.py",
    ),
    define(
        id="portfolio.job.on",
        domain="portfolio",
        description="Optionalen Portfolio-Kursjob nach ausdruecklichem Nutzerauftrag einschalten",
        command="./scripts/assistant.sh jobs on portfolio",
        mode="local-write",
        writes_external_data=False,
        approval="explicit-user-start",
        availability="always",
        documentation_anchor="docs/PORTFOLIO_ADVISOR.md",
        test_anchor="tests/test_portfolio_tool.py",
    ),
    define(
        id="portfolio.job.restart",
        domain="portfolio",
        description="Portfolio-Kursjob nach ausdruecklichem Nutzerauftrag neu starten",
        command="./scripts/assistant.sh jobs restart portfolio",
        mode="local-write",
        writes_external_data=False,
        approval="explicit-user-restart",
        availability="always",
        documentation_anchor="docs/PORTFOLIO_ADVISOR.md",
        test_anchor="tests/test_portfolio_tool.py",
    ),
    define(
        id="portfolio.job.off",
        domain="portfolio",
        description="Portfolio-Kursjob nach ausdruecklichem Nutzerauftrag ausschalten",
        command="./scripts/assistant.sh jobs off portfolio",
        mode="local-write",
        writes_external_data=False,
        approval="explicit-user-stop",
        availability="always",
        documentation_anchor="docs/PORTFOLIO_ADVISOR.md",
        test_anchor="tests/test_portfolio_tool.py",
    ),
)
