from __future__ import annotations

from personal_assistant.contracts.tools import ToolDefinition, define

TOOLS: tuple[ToolDefinition, ...] = (
    define(
        id="portfolio.status",
        domain="portfolio",
        description="Depotbestand, Watchlist, Kursabdeckung und Datenfrische anzeigen",
        command="./scripts/assistant.sh portfolio status",
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="always",
        documentation_anchor="docs/PORTFOLIO_ADVISOR.md",
        test_anchor="tests/test_portfolio_tool.py",
    ),
    define(
        id="portfolio.setup",
        domain="portfolio",
        description="Portfolio-Monitor fuer den bezahlten EODHD-Zugang auf 15-Minuten-Abrufe konfigurieren; API-Schluessel und Job bleiben getrennt",
        command="./scripts/assistant.sh setup portfolio --provider eodhd --interval-minutes 15 --approve-permissions",
        mode="local-write",
        writes_external_data=False,
        approval="explicit-user-permission-setup",
        availability="always",
        documentation_anchor="docs/PORTFOLIO_ADVISOR.md",
        test_anchor="tests/test_portfolio_tool.py",
    ),
    define(
        id="portfolio.doctor",
        domain="portfolio",
        description="Portfolio-Datenbank, Anbieter-Konfiguration und Pflichtkurse pruefen",
        command="./scripts/assistant.sh portfolio doctor",
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="always",
        documentation_anchor="docs/PORTFOLIO_ADVISOR.md",
        test_anchor="tests/test_portfolio_tool.py",
    ),
    define(
        id="portfolio.import.pp",
        domain="portfolio",
        description="ClamAV-gepruefte Portfolio-Performance-XML zuerst als Vorschau importieren",
        command='./scripts/assistant.sh portfolio import-pp --file "<Datei-im-Importordner>" --dry-run',
        mode="local-write",
        writes_external_data=False,
        approval="explicit-user-import-with-preview",
        availability="always",
        documentation_anchor="docs/PORTFOLIO_ADVISOR.md",
        test_anchor="tests/test_portfolio_tool.py",
    ),
    define(
        id="portfolio.import.pp.confirm",
        domain="portfolio",
        description="Zuvor geprueften Portfolio-Snapshot nach ausdruecklichem Nutzerauftrag lokal importieren",
        command='./scripts/assistant.sh portfolio import-pp --file "<Datei-im-Importordner>" --yes',
        mode="local-write",
        writes_external_data=False,
        approval="explicit-user-confirmed-import",
        availability="always",
        documentation_anchor="docs/PORTFOLIO_ADVISOR.md",
        test_anchor="tests/test_portfolio_tool.py",
    ),
    define(
        id="portfolio.import.csv",
        domain="portfolio",
        description="ClamAV-geprueften DKB-CSV-Depotsnapshot aus dem kontrollierten Importordner zuerst als Vorschau einlesen",
        command='./scripts/assistant.sh portfolio import-csv --file "<Datei-im-Importordner>" --dry-run',
        mode="local-write",
        writes_external_data=False,
        approval="explicit-user-import-with-preview",
        availability="always",
        documentation_anchor="docs/PORTFOLIO_ADVISOR.md",
        test_anchor="tests/test_portfolio_tool.py",
    ),
    define(
        id="portfolio.import.csv.nextcloud",
        domain="portfolio",
        description="Exakt ausgewaehlte datierte DKB-CSV aus dem konfigurierten Nextcloud-Portfolioordner herunterladen, scannen und als Vorschau einlesen",
        command='./scripts/assistant.sh portfolio import-csv --nextcloud-path "Assistent/Finanzen/Portfolio/<Datei-DD.MM.YYYY.csv>" --dry-run',
        mode="local-write",
        writes_external_data=False,
        approval="explicit-user-import-with-preview",
        availability="always",
        documentation_anchor="docs/PORTFOLIO_ADVISOR.md",
        test_anchor="tests/test_portfolio_tool.py",
    ),
    define(
        id="portfolio.import.csv.confirm",
        domain="portfolio",
        description="Zuvor geprueften lokalen DKB-CSV-Depotsnapshot nach ausdruecklichem Nutzerauftrag importieren",
        command='./scripts/assistant.sh portfolio import-csv --file "<Datei-im-Importordner>" --yes',
        mode="local-write",
        writes_external_data=False,
        approval="explicit-user-confirmed-import",
        availability="always",
        documentation_anchor="docs/PORTFOLIO_ADVISOR.md",
        test_anchor="tests/test_portfolio_tool.py",
    ),
    define(
        id="portfolio.import.csv.nextcloud.confirm",
        domain="portfolio",
        description="Zuvor geprueften DKB-CSV-Depotsnapshot aus dem exakten Nextcloud-Pfad nach ausdruecklichem Nutzerauftrag importieren",
        command='./scripts/assistant.sh portfolio import-csv --nextcloud-path "Assistent/Finanzen/Portfolio/<Datei-DD.MM.YYYY.csv>" --yes',
        mode="local-write",
        writes_external_data=False,
        approval="explicit-user-confirmed-import",
        availability="always",
        documentation_anchor="docs/PORTFOLIO_ADVISOR.md",
        test_anchor="tests/test_portfolio_tool.py",
    ),
    define(
        id="portfolio.holdings",
        domain="portfolio",
        description="Eigene Aktien, Wertpapiere und Depotpositionen aus dem letzten unveraenderlich gespeicherten Snapshot anzeigen",
        command="./scripts/assistant.sh portfolio holdings",
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="always",
        documentation_anchor="docs/PORTFOLIO_ADVISOR.md",
        test_anchor="tests/test_portfolio_tool.py",
    ),
    define(
        id="portfolio.valuation",
        domain="portfolio",
        description="Aktuellen Depotwert und Gewinn deterministisch aus gespeicherten EODHD-Aktienkursen und zeitgestempelten EODHD-Wechselkursen berechnen; bei fehlender Umrechnung fail-closed",
        command="./scripts/assistant.sh portfolio valuation",
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="always",
        documentation_anchor="docs/PORTFOLIO_ADVISOR.md",
        test_anchor="tests/test_portfolio_tool.py",
    ),
    define(
        id="portfolio.watchlist",
        domain="portfolio",
        description="Watchlist und bestaetigte ISIN/Symbol/MIC-Zuordnungen anzeigen",
        command="./scripts/assistant.sh portfolio watchlist list",
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="always",
        documentation_anchor="docs/PORTFOLIO_ADVISOR.md",
        test_anchor="tests/test_portfolio_tool.py",
    ),
    define(
        id="portfolio.mapping.suggest",
        domain="portfolio",
        description="Exakte EODHD-ISIN-Treffer abrufen, Ollama nur aus providerseitig belegten Kandidaten auswaehlen lassen und die vollstaendige genehmigungspflichtige watchlist-add-Folgeaktion liefern",
        command='./scripts/assistant.sh portfolio mapping suggest --isin "<ISIN>"',
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="always",
        documentation_anchor="docs/PORTFOLIO_ADVISOR.md",
        test_anchor="tests/test_portfolio_tool.py",
    ),
    define(
        id="portfolio.mapping.discover",
        domain="portfolio",
        description="Wertpapiername oder Symbol bei EODHD suchen, eine eindeutige providerseitige ISIN ermitteln und daraus Vorschlag sowie vollstaendige genehmigungspflichtige watchlist-add-Folgeaktion erzeugen",
        command='./scripts/assistant.sh portfolio mapping suggest --query "<Unternehmen-oder-Symbol>"',
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="always",
        documentation_anchor="docs/PORTFOLIO_ADVISOR.md",
        test_anchor="tests/test_portfolio_tool.py",
    ),
    define(
        id="portfolio.watchlist.add",
        domain="portfolio",
        description="Wertpapier nur mit den unveraenderten Feldern einer explizit bestaetigten Mapping-Folgeaktion aufnehmen; portfolio mapping add existiert nicht",
        command='./scripts/assistant.sh portfolio watchlist add --isin "<ISIN>" --name "<Name>" --symbol "<Symbol>" --mic "<MIC>" --currency "<ISO>" --yes',
        mode="local-write",
        writes_external_data=False,
        approval="explicit-user-watchlist-change",
        availability="always",
        documentation_anchor="docs/PORTFOLIO_ADVISOR.md",
        test_anchor="tests/test_portfolio_tool.py",
    ),
    define(
        id="portfolio.watchlist.disable",
        domain="portfolio",
        description="Watchlist-Eintrag nach Nutzerauftrag deaktivieren, ohne Historie zu loeschen",
        command='./scripts/assistant.sh portfolio watchlist disable --isin "<ISIN>" --yes',
        mode="local-write",
        writes_external_data=False,
        approval="explicit-user-watchlist-change",
        availability="always",
        documentation_anchor="docs/PORTFOLIO_ADVISOR.md",
        test_anchor="tests/test_portfolio_tool.py",
    ),
    define(
        id="portfolio.quotes.status",
        domain="portfolio",
        description="Pflichtkurs-Abdeckung, Alter und letzten Abrufstatus anzeigen",
        command="./scripts/assistant.sh portfolio quotes status",
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="always",
        documentation_anchor="docs/PORTFOLIO_ADVISOR.md",
        test_anchor="tests/test_portfolio_tool.py",
    ),
    define(
        id="portfolio.quotes.get",
        domain="portfolio",
        description="Letzten gespeicherten Kurswert, Waehrung, Quelle und Zeitstempel fuer eine exakte ISIN anzeigen",
        command='./scripts/assistant.sh portfolio quotes get --isin "<ISIN>"',
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="always",
        documentation_anchor="docs/PORTFOLIO_ADVISOR.md",
        test_anchor="tests/test_portfolio_tool.py",
    ),
    define(
        id="portfolio.quotes.refresh",
        domain="portfolio",
        description="Faellige EODHD-Live/Delayed-Kurse gebuendelt abrufen, Quellzeit und Empfangszeit speichern und Pflichtluecken fail-closed melden",
        command="./scripts/assistant.sh portfolio quotes refresh",
        mode="local-write",
        writes_external_data=False,
        approval="scheduled-market-data-refresh",
        availability="always",
        documentation_anchor="docs/PORTFOLIO_ADVISOR.md",
        test_anchor="tests/test_portfolio_tool.py",
    ),
    define(
        id="portfolio.quotes.refresh.force",
        domain="portfolio",
        description="Kursabruf fuer eine gezielte Diagnose vor dem naechsten Faelligkeitszeitpunkt erzwingen",
        command="./scripts/assistant.sh portfolio quotes refresh --force",
        mode="local-write",
        writes_external_data=False,
        approval="explicit-user-diagnostic-refresh",
        availability="always",
        documentation_anchor="docs/PORTFOLIO_ADVISOR.md",
        test_anchor="tests/test_portfolio_tool.py",
    ),
    define(
        id="portfolio.analyze",
        domain="portfolio",
        description="Gespeicherte Kursreihe mit deterministischen Trendindikatoren analysieren",
        command='./scripts/assistant.sh portfolio analyze --isin "<ISIN>"',
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="always",
        documentation_anchor="docs/PORTFOLIO_ADVISOR.md",
        test_anchor="tests/test_portfolio_tool.py",
    ),
    define(
        id="portfolio.alerts",
        domain="portfolio",
        description="Kursmarken und deduplizierte Uebertrittsereignisse anzeigen",
        command="./scripts/assistant.sh portfolio alerts list",
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="always",
        documentation_anchor="docs/PORTFOLIO_ADVISOR.md",
        test_anchor="tests/test_portfolio_tool.py",
    ),
    define(
        id="portfolio.alerts.add",
        domain="portfolio",
        description="Kursmarke mit Hysterese und Abklingzeit nach Nutzerauftrag anlegen",
        command='./scripts/assistant.sh portfolio alerts add --isin "<ISIN>" --direction "<above|below>" --threshold "<Kurs>" --currency "<ISO>" --yes',
        mode="local-write",
        writes_external_data=False,
        approval="explicit-user-alert-change",
        availability="always",
        documentation_anchor="docs/PORTFOLIO_ADVISOR.md",
        test_anchor="tests/test_portfolio_tool.py",
    ),
    define(
        id="portfolio.alerts.disable",
        domain="portfolio",
        description="Kursalarm nach Nutzerauftrag deaktivieren, ohne Ereignishistorie zu loeschen",
        command='./scripts/assistant.sh portfolio alerts disable --id "<Regel-ID>" --yes',
        mode="local-write",
        writes_external_data=False,
        approval="explicit-user-alert-change",
        availability="always",
        documentation_anchor="docs/PORTFOLIO_ADVISOR.md",
        test_anchor="tests/test_portfolio_tool.py",
    ),
    define(
        id="portfolio.performance",
        domain="portfolio",
        description="Signalqualitaet getrennt von der technischen Agentengesundheit auswerten",
        command="./scripts/assistant.sh portfolio performance",
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="always",
        documentation_anchor="docs/PORTFOLIO_ADVISOR.md",
        test_anchor="tests/test_portfolio_tool.py",
    ),
    define(
        id="portfolio.job.on",
        domain="portfolio",
        description="Optionalen Portfolio-Kursjob nach ausdruecklichem Nutzerauftrag einschalten",
        command="./scripts/assistant.sh jobs on portfolio",
        mode="local-write",
        writes_external_data=False,
        approval="explicit-user-start",
        availability="always",
        documentation_anchor="docs/PORTFOLIO_ADVISOR.md",
        test_anchor="tests/test_portfolio_tool.py",
    ),
    define(
        id="portfolio.job.restart",
        domain="portfolio",
        description="Portfolio-Kursjob nach ausdruecklichem Nutzerauftrag neu starten",
        command="./scripts/assistant.sh jobs restart portfolio",
        mode="local-write",
        writes_external_data=False,
        approval="explicit-user-restart",
        availability="always",
        documentation_anchor="docs/PORTFOLIO_ADVISOR.md",
        test_anchor="tests/test_portfolio_tool.py",
    ),
    define(
        id="portfolio.job.off",
        domain="portfolio",
        description="Portfolio-Kursjob nach ausdruecklichem Nutzerauftrag ausschalten",
        command="./scripts/assistant.sh jobs off portfolio",
        mode="local-write",
        writes_external_data=False,
        approval="explicit-user-stop",
        availability="always",
        documentation_anchor="docs/PORTFOLIO_ADVISOR.md",
        test_anchor="tests/test_portfolio_tool.py",
    ),
)
