from __future__ import annotations

from personal_assistant.contracts.tools import ToolDefinition, define

TOOLS: tuple[ToolDefinition, ...] = (
    define(
        id="assistant.status",
        domain="runtime",
        description="Core, Ressourcen, Policies und Connector-Status anzeigen",
        command="./scripts/assistant.sh status",
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="always",
        documentation_anchor="AGENTS.md",
        test_anchor="tests/test_m5_tool_contract.py",
    ),
    define(
        id="assistant.version",
        domain="runtime",
        description=(
            "Installiertes OpenClaw-Local-Personal-Assistant-Produktrelease und Konsistenz "
            "aus RELEASE.json pruefen; keine eingebettete Core-, Plugin- oder CLI-Version"
        ),
        command="./scripts/assistant.sh version --verify",
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="always",
        documentation_anchor="AGENTS.md",
        test_anchor="tests/test_m5_tool_contract.py",
    ),
    define(
        id="assistant.version.history",
        domain="runtime",
        description="Aenderungen der installierten und vorherigen Updates maschinenlesbar anzeigen",
        command="./scripts/assistant.sh version --verify --history --limit 10",
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="always",
        documentation_anchor="AGENTS.md",
        test_anchor="tests/test_m5_tool_contract.py",
    ),
    define(
        id="assistant.version.since",
        domain="runtime",
        description="Alle bekannten Aenderungen seit einer genannten Version anzeigen",
        command='./scripts/assistant.sh version --verify --history --since "<Version>" --limit 20',
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="always",
        documentation_anchor="AGENTS.md",
        test_anchor="tests/test_m5_tool_contract.py",
    ),
    define(
        id="assistant.search",
        domain="runtime",
        description="E-Mails, Nextcloud-Dateien, Kontakte und Kalender lokal durchsuchen",
        command='./scripts/assistant.sh search "<Suchbegriff>"',
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="always",
        documentation_anchor="AGENTS.md",
        test_anchor="tests/test_m5_tool_contract.py",
    ),
    define(
        id="assistant.setup.standard-operations",
        domain="runtime",
        description=(
            "Standardprofil einer eingeschraenkten oder unvollstaendig migrierten "
            "Instanz pruefen und fuer bestaetigte Ressourcen lokal aktivieren"
        ),
        command="./scripts/assistant.sh setup standard-operations --yes",
        mode="local-write",
        writes_external_data=False,
        approval="explicit-user-standard-operations-profile",
        availability="always",
        documentation_anchor="docs/STANDARD_OPERATIONS.md",
        test_anchor="tests/test_standard_operations_profile.py",
    ),
    define(
        id="assistant.monitor.status",
        domain="runtime",
        description="Evidenzbasierten Gesundheitswert, Teilwerte und konkrete Probleme anzeigen",
        command="./scripts/assistant.sh monitor status --days 7 --live",
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="always",
        documentation_anchor="AGENTS.md",
        test_anchor="tests/test_m5_tool_contract.py",
    ),
    define(
        id="assistant.jobs.status",
        domain="runtime",
        description="Soll-/Ist-Zustand der freigegebenen Hintergrundjobs anzeigen",
        command="./scripts/assistant.sh jobs status --target all",
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="always",
        documentation_anchor="AGENTS.md",
        test_anchor="tests/test_m5_tool_contract.py",
    ),
    define(
        id="assistant.scheduler.status",
        domain="runtime",
        description="Adaptive Aufgaben-Queue, aktive Leases, Wartezeiten und letzte Laeufe anzeigen",
        command="./scripts/assistant.sh scheduler status",
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="always",
        documentation_anchor="AGENTS.md",
        test_anchor="tests/test_m5_tool_contract.py",
    ),
    define(
        id="assistant.scheduler.doctor",
        domain="runtime",
        description="Scheduler-Datenbank, Fristverletzungen und abgelaufene Leases pruefen",
        command="./scripts/assistant.sh scheduler doctor",
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="always",
        documentation_anchor="AGENTS.md",
        test_anchor="tests/test_m5_tool_contract.py",
    ),
    define(
        id="assistant.scheduler.activity",
        domain="runtime",
        description="Aktive zeitlich begrenzte Themenprioritaeten anzeigen",
        command="./scripts/assistant.sh scheduler activity",
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="always",
        documentation_anchor="AGENTS.md",
        test_anchor="tests/test_m5_tool_contract.py",
    ),
    define(
        id="assistant.scheduler.focus",
        domain="runtime",
        description="Ein explizites aktuelles Nutzerthema lokal und zeitlich begrenzt priorisieren",
        command='./scripts/assistant.sh scheduler focus --topic "<mail|portfolio|knowledge|planning|operations>" --minutes 30',
        mode="local-write",
        writes_external_data=False,
        approval="adaptive-local-focus-only",
        availability="always",
        documentation_anchor="AGENTS.md",
        test_anchor="tests/test_m5_tool_contract.py",
    ),
    define(
        id="assistant.jobs.check",
        domain="runtime",
        description="Hintergrundjobs pruefen, Alerts aktualisieren und die eng begrenzte Mail-Dry-Run-Sperre automatisch beheben",
        command="./scripts/assistant.sh jobs check --target all --deep",
        mode="local-write",
        writes_external_data=False,
        approval="job-monitoring-and-safe-mail-recovery",
        availability="always",
        documentation_anchor="AGENTS.md",
        test_anchor="tests/test_m5_tool_contract.py",
    ),
    define(
        id="assistant.jobs.alerts",
        domain="runtime",
        description="Aktive Job-Ausfaelle und den letzten beobachteten Zustand anzeigen",
        command="./scripts/assistant.sh jobs alerts",
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="always",
        documentation_anchor="AGENTS.md",
        test_anchor="tests/test_m5_tool_contract.py",
    ),
    define(
        id="assistant.jobs.on",
        domain="runtime",
        description="Standardfunktionen nach ausdruecklichem Nutzerauftrag sicher einschalten",
        command="./scripts/assistant.sh jobs on standard",
        mode="local-write",
        writes_external_data=False,
        approval="explicit-user-start",
        availability="always",
        documentation_anchor="AGENTS.md",
        test_anchor="tests/test_m5_tool_contract.py",
    ),
    define(
        id="assistant.jobs.restart",
        domain="runtime",
        description="Standardfunktionen nach ausdruecklichem Nutzerauftrag reparieren und neu starten",
        command="./scripts/assistant.sh jobs restart standard",
        mode="local-write",
        writes_external_data=False,
        approval="explicit-user-restart",
        availability="always",
        documentation_anchor="AGENTS.md",
        test_anchor="tests/test_m5_tool_contract.py",
    ),
    define(
        id="assistant.jobs.off",
        domain="runtime",
        description="Produktive Standardjobs nach ausdruecklichem Nutzerauftrag ausschalten",
        command="./scripts/assistant.sh jobs off standard",
        mode="local-write",
        writes_external_data=False,
        approval="explicit-user-stop",
        availability="always",
        documentation_anchor="AGENTS.md",
        test_anchor="tests/test_m5_tool_contract.py",
    ),
    define(
        id="assistant.ollama.status",
        domain="runtime",
        description="Ollama-Prioritaetskoordinator, Queue und Upstream-Zustand anzeigen",
        command="./scripts/assistant.sh ollama status",
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="always",
        documentation_anchor="AGENTS.md",
        test_anchor="tests/test_m5_tool_contract.py",
    ),
    define(
        id="assistant.ollama.check",
        domain="runtime",
        description="Ollama-Upstream ueber den lokalen Prioritaetskoordinator live pruefen",
        command="./scripts/assistant.sh ollama check",
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="always",
        documentation_anchor="AGENTS.md",
        test_anchor="tests/test_m5_tool_contract.py",
    ),
    define(
        id="assistant.ollama.queue",
        domain="runtime",
        description="Aktive und wartende Modellauftraege mit Prioritaeten anzeigen",
        command="./scripts/assistant.sh ollama queue",
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="always",
        documentation_anchor="AGENTS.md",
        test_anchor="tests/test_m5_tool_contract.py",
    ),
    define(
        id="assistant.ollama.start",
        domain="runtime",
        description="Ollama-Prioritaetskoordinator nach ausdruecklichem Nutzerauftrag starten",
        command="./scripts/assistant.sh ollama start",
        mode="local-write",
        writes_external_data=False,
        approval="explicit-user-start",
        availability="always",
        documentation_anchor="AGENTS.md",
        test_anchor="tests/test_m5_tool_contract.py",
    ),
    define(
        id="assistant.ollama.restart",
        domain="runtime",
        description="Ollama-Prioritaetskoordinator nach ausdruecklichem Nutzerauftrag neu starten und verifizieren",
        command="./scripts/assistant.sh ollama restart",
        mode="local-write",
        writes_external_data=False,
        approval="explicit-user-restart",
        availability="always",
        documentation_anchor="AGENTS.md",
        test_anchor="tests/test_m5_tool_contract.py",
    ),
    define(
        id="assistant.performance.mail",
        domain="runtime",
        description="Privacy-sichere Laufzeit-, Queue- und Ollama-Metriken des Mail-Interfaces auswerten",
        command="./scripts/assistant.sh performance mail --limit 20",
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="always",
        documentation_anchor="AGENTS.md",
        test_anchor="tests/test_m5_tool_contract.py",
    ),
    define(
        id="assistant.monitor.record",
        domain="runtime",
        description="Monitoring-Snapshot lokal fuer Trendanalyse speichern",
        command="./scripts/assistant.sh monitor record --days 7 --live",
        mode="local-write",
        writes_external_data=False,
        approval="monitoring-local-only",
        availability="always",
        documentation_anchor="AGENTS.md",
        test_anchor="tests/test_m5_tool_contract.py",
    ),
    define(
        id="assistant.monitor.history",
        domain="runtime",
        description="Gesundheitswert und Trend der letzten 30 Tage anzeigen",
        command="./scripts/assistant.sh monitor history --days 30",
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="always",
        documentation_anchor="AGENTS.md",
        test_anchor="tests/test_m5_tool_contract.py",
    ),
)
