from __future__ import annotations

from personal_assistant.contracts.tools import ToolDefinition, define

TOOLS: tuple[ToolDefinition, ...] = (
    define(
        id="nextcloud.tasks.discover",
        domain="tasks",
        description="Erreichbare Nextcloud-Aufgabenlisten read-only mit VTODO-Unterstuetzung und Serverrechten auflisten",
        command="./scripts/assistant.sh tasks discover",
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="always",
        documentation_anchor="docs/DIRECT_TASKS.md",
        test_anchor="tests/test_direct_tasks_tool.py",
    ),
    define(
        id="nextcloud.tasks.configure",
        domain="tasks",
        description="Eine zuvor entdeckte Aufgabenliste nach ausdruecklicher Nutzerwahl konfigurieren; Aktualisierungsrecht nur mit --allow-update",
        command='./scripts/assistant.sh tasks configure --resource "<resource_id>" --allow-update --yes',
        mode="local-write",
        writes_external_data=False,
        approval="explicit-user-task-list-selection",
        availability="always",
        documentation_anchor="docs/DIRECT_TASKS.md",
        test_anchor="tests/test_direct_tasks_tool.py",
    ),
    define(
        id="nextcloud.tasks.status",
        domain="tasks",
        description="Konfiguration sowie Lese-, Anlege- und Aktualisierungsrechte des Nextcloud-Aufgabenwerkzeugs pruefen",
        command="./scripts/assistant.sh tasks status",
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="tasks",
        documentation_anchor="docs/DIRECT_TASKS.md",
        test_anchor="tests/test_direct_tasks_tool.py",
    ),
    define(
        id="nextcloud.tasks.list",
        domain="tasks",
        description="Aufgaben aus der freigegebenen Nextcloud-Aufgabenliste mit UID lesen",
        command="./scripts/assistant.sh tasks list --include-completed --limit 100",
        mode="read",
        writes_external_data=False,
        approval="none",
        availability="tasks-list",
        documentation_anchor="docs/DIRECT_TASKS.md",
        test_anchor="tests/test_direct_tasks_tool.py",
    ),
    define(
        id="nextcloud.tasks.update",
        domain="tasks",
        description="Eine zuvor eindeutig per UID ausgewaehlte Aufgabe nach ausdruecklichem Nutzerauftrag ETag-geschuetzt aktualisieren oder abschliessen; Serien nur mit gesonderter Freigabe",
        command='./scripts/assistant.sh tasks update --uid "<UID>" --expected-title "<aktueller Titel>" --due "<YYYY-MM-DD oder ISO-8601>" --yes',
        mode="write",
        writes_external_data=True,
        approval="explicit-user-task-update-etag-guarded",
        availability="tasks-update",
        documentation_anchor="docs/DIRECT_TASKS.md",
        test_anchor="tests/test_direct_tasks_tool.py",
    ),
    define(
        id="nextcloud.tasks.create",
        domain="tasks",
        description="Neue Aufgabe in der freigegebenen Nextcloud-Aufgabenliste anlegen",
        command='./scripts/assistant.sh tasks create --title "<Titel>" --due "<YYYY-MM-DD oder ISO-8601>" --priority <0-9> --description "<Beschreibung>"',
        mode="write",
        writes_external_data=True,
        approval="configured-tasks-create-only",
        availability="tasks-create",
        documentation_anchor="docs/DIRECT_TASKS.md",
        test_anchor="tests/test_direct_tasks_tool.py",
    ),
)
